/**
 * Rendimientos estándar de limpieza por alimento — TABLA GLOBAL de referencia.
 *
 * Fuente: USDA SR-28 (dominio público), campo Refuse de FOOD_DES.txt:
 *   rendimiento = 100 − refuse. Cada entrada lleva su NDB de origen (auditable).
 * Curada a mano para hostelería española (2026-08-05): 70 entradas, nombres de
 * cocina + aliases para el matching. Cortes de carne renombrados tras revisar
 * la nomenclatura americana (tenderloin=solomillo, brisket=pecho...).
 * Pescado: fase 2 (SR-28 solo lista filetes ya limpios, sin merma).
 *
 * NO se inventó ningún número: si el USDA no tenía la fila, no hay entrada.
 */
module.exports = [
    { nombre: 'Cordero (canal, cortes magros y grasa)', aliases: ["cordero"], familia: 'carne', rendimiento: 77, queSeQuita: 'hueso', fuente: 'USDA SR-28 #17001' },
    { nombre: 'Costilla de cerdo', aliases: ["costillas", "costillar de cerdo"], familia: 'carne', rendimiento: 70, queSeQuita: 'hueso', fuente: 'USDA SR-28 #10088' },
    { nombre: 'Costillar de vacuno (short ribs)', aliases: ["costillar", "churrasco de ternera"], familia: 'carne', rendimiento: 71, queSeQuita: 'hueso y grasa exterior', fuente: 'USDA SR-28 #13148' },
    { nombre: 'Lomo de cerdo entero', aliases: ["lomo de cerdo", "cinta de lomo", "lomo"], familia: 'carne', rendimiento: 79, queSeQuita: 'hueso y grasa exterior', fuente: 'USDA SR-28 #10022' },
    { nombre: 'Paletilla de cordero', aliases: ["paletilla"], familia: 'carne', rendimiento: 76, queSeQuita: 'hueso', fuente: 'USDA SR-28 #17037' },
    { nombre: 'Panceta fresca', aliases: ["panceta", "bacon fresco"], familia: 'carne', rendimiento: 93, queSeQuita: 'recortes', fuente: 'USDA SR-28 #10005' },
    { nombre: 'Pato entero (carne y piel)', aliases: ["pato"], familia: 'carne', rendimiento: 72, queSeQuita: 'huesos y despojos', fuente: 'USDA SR-28 #05139' },
    { nombre: 'Pavo entero', aliases: ["pavo"], familia: 'carne', rendimiento: 71, queSeQuita: 'huesos y despojos', fuente: 'USDA SR-28 #05165' },
    { nombre: 'Pecho de ternera (brisket)', aliases: ["pecho", "brisket"], familia: 'carne', rendimiento: 70, queSeQuita: 'grasa exterior', fuente: 'USDA SR-28 #13023' },
    { nombre: 'Pechuga de pollo con hueso', aliases: ["pechuga", "pechugas"], familia: 'carne', rendimiento: 80, queSeQuita: 'hueso', fuente: 'USDA SR-28 #05057' },
    { nombre: 'Pierna de cerdo (jamón fresco)', aliases: ["pernil", "jamon fresco", "pierna de cerdo"], familia: 'carne', rendimiento: 80, queSeQuita: 'hueso y corteza', fuente: 'USDA SR-28 #10009' },
    { nombre: 'Pierna de cordero con hueso', aliases: ["pierna de cordero", "gigot"], familia: 'carne', rendimiento: 59, queSeQuita: 'hueso', fuente: 'USDA SR-28 #17022' },
    { nombre: 'Pollo entero (carne y piel)', aliases: ["pollo", "pollo entero"], familia: 'carne', rendimiento: 68, queSeQuita: 'huesos y despojos', fuente: 'USDA SR-28 #05006' },
    { nombre: 'Pollo entero (solo carne)', aliases: ["pollo limpio", "carne de pollo"], familia: 'carne', rendimiento: 48, queSeQuita: 'huesos, piel y despojos', fuente: 'USDA SR-28 #05011' },
    { nombre: 'Solomillo de cerdo', aliases: ["solomillo cerdo", "solomillo de cerdo"], familia: 'carne', rendimiento: 95, queSeQuita: 'grasa y tejido conjuntivo', fuente: 'USDA SR-28 #10060' },
    { nombre: 'Vacío de ternera (flank)', aliases: ["vacio", "vacío"], familia: 'carne', rendimiento: 96, queSeQuita: 'grasa y tejido', fuente: 'USDA SR-28 #13068' },
    { nombre: 'Aguacate', aliases: ["aguacates", "palta"], familia: 'fruta', rendimiento: 74, queSeQuita: 'piel y hueso', fuente: 'USDA SR-28 #09037' },
    { nombre: 'Cereza', aliases: ["cerezas", "picotas"], familia: 'fruta', rendimiento: 92, queSeQuita: 'hueso y pedúnculo', fuente: 'USDA SR-28 #09070' },
    { nombre: 'Ciruela', aliases: ["ciruelas"], familia: 'fruta', rendimiento: 94, queSeQuita: 'hueso y pedúnculo', fuente: 'USDA SR-28 #09279' },
    { nombre: 'Fresa', aliases: ["fresas", "fresón", "freson"], familia: 'fruta', rendimiento: 94, queSeQuita: 'pedúnculo y hojas', fuente: 'USDA SR-28 #09316' },
    { nombre: 'Granada', aliases: ["granadas"], familia: 'fruta', rendimiento: 56, queSeQuita: 'corteza y membranas', fuente: 'USDA SR-28 #09286' },
    { nombre: 'Higo', aliases: ["higos"], familia: 'fruta', rendimiento: 99, queSeQuita: 'pedúnculo', fuente: 'USDA SR-28 #09089' },
    { nombre: 'Kiwi', aliases: ["kiwis"], familia: 'fruta', rendimiento: 76, queSeQuita: 'piel y extremos', fuente: 'USDA SR-28 #09148' },
    { nombre: 'Limón', aliases: ["limones", "limon"], familia: 'fruta', rendimiento: 53, queSeQuita: 'piel y semillas (zumo/pulpa)', fuente: 'USDA SR-28 #09150' },
    { nombre: 'Mango', aliases: ["mangos"], familia: 'fruta', rendimiento: 71, queSeQuita: 'piel y hueso', fuente: 'USDA SR-28 #09176' },
    { nombre: 'Manzana', aliases: ["manzanas"], familia: 'fruta', rendimiento: 90, queSeQuita: 'corazón y pedúnculo (con piel)', fuente: 'USDA SR-28 #09003' },
    { nombre: 'Melocotón', aliases: ["melocoton", "melocotones", "durazno"], familia: 'fruta', rendimiento: 96, queSeQuita: 'hueso y pedúnculo', fuente: 'USDA SR-28 #09236' },
    { nombre: 'Melón cantalupo', aliases: ["melon", "melón"], familia: 'fruta', rendimiento: 51, queSeQuita: 'corteza y semillas', fuente: 'USDA SR-28 #09181' },
    { nombre: 'Naranja', aliases: ["naranjas"], familia: 'fruta', rendimiento: 73, queSeQuita: 'piel y semillas', fuente: 'USDA SR-28 #09200' },
    { nombre: 'Papaya', aliases: ["papayas"], familia: 'fruta', rendimiento: 62, queSeQuita: 'piel y semillas', fuente: 'USDA SR-28 #09226' },
    { nombre: 'Pera', aliases: ["peras"], familia: 'fruta', rendimiento: 90, queSeQuita: 'corazón y pedúnculo (con piel)', fuente: 'USDA SR-28 #09252' },
    { nombre: 'Piña', aliases: ["pina", "piñas", "ananás"], familia: 'fruta', rendimiento: 51, queSeQuita: 'corteza, corona y tronco', fuente: 'USDA SR-28 #09266' },
    { nombre: 'Plátano', aliases: ["platano", "banana", "plátanos"], familia: 'fruta', rendimiento: 64, queSeQuita: 'piel', fuente: 'USDA SR-28 #09040' },
    { nombre: 'Sandía', aliases: ["sandia", "sandías"], familia: 'fruta', rendimiento: 52, queSeQuita: 'corteza y semillas', fuente: 'USDA SR-28 #09326' },
    { nombre: 'Uva', aliases: ["uvas"], familia: 'fruta', rendimiento: 96, queSeQuita: 'raspón y pieles dañadas', fuente: 'USDA SR-28 #09132' },
    { nombre: 'Gamba cruda', aliases: ["gambas", "langostino", "langostinos", "camarón"], familia: 'marisco', rendimiento: 87, queSeQuita: 'cabeza, cola y cáscara', fuente: 'USDA SR-28 #15270' },
    { nombre: 'Ajo', aliases: ["ajos", "cabeza de ajo"], familia: 'verdura', rendimiento: 87, queSeQuita: 'piel y base', fuente: 'USDA SR-28 #11215' },
    { nombre: 'Alcachofa', aliases: ["alcachofas"], familia: 'verdura', rendimiento: 40, queSeQuita: 'hojas exteriores y tallo', fuente: 'USDA SR-28 #11007' },
    { nombre: 'Apio', aliases: ["apios"], familia: 'verdura', rendimiento: 89, queSeQuita: 'base y hojas duras', fuente: 'USDA SR-28 #11143' },
    { nombre: 'Berenjena', aliases: ["berenjenas"], familia: 'verdura', rendimiento: 81, queSeQuita: 'pedúnculo y extremos', fuente: 'USDA SR-28 #11209' },
    { nombre: 'Boniato', aliases: ["batata", "camote", "boniatos"], familia: 'verdura', rendimiento: 72, queSeQuita: 'piel y extremos', fuente: 'USDA SR-28 #11507' },
    { nombre: 'Brócoli', aliases: ["brocoli", "brécol"], familia: 'verdura', rendimiento: 61, queSeQuita: 'tallo leñoso y hojas', fuente: 'USDA SR-28 #11090' },
    { nombre: 'Calabacín', aliases: ["calabacin", "calabacines"], familia: 'verdura', rendimiento: 95, queSeQuita: 'extremos', fuente: 'USDA SR-28 #11477' },
    { nombre: 'Calabaza', aliases: ["calabazas"], familia: 'verdura', rendimiento: 70, queSeQuita: 'piel, semillas y fibra', fuente: 'USDA SR-28 #11422' },
    { nombre: 'Cebolla', aliases: ["cebollas", "cebolla blanca"], familia: 'verdura', rendimiento: 90, queSeQuita: 'piel y extremos', fuente: 'USDA SR-28 #11282' },
    { nombre: 'Champiñón', aliases: ["champiñones", "champinon", "champis"], familia: 'verdura', rendimiento: 97, queSeQuita: 'base del pie', fuente: 'USDA SR-28 #11260' },
    { nombre: 'Col lombarda', aliases: ["lombarda", "col roja"], familia: 'verdura', rendimiento: 80, queSeQuita: 'hojas exteriores y tronco', fuente: 'USDA SR-28 #11112' },
    { nombre: 'Coliflor', aliases: ["coliflores"], familia: 'verdura', rendimiento: 39, queSeQuita: 'hojas y tronco', fuente: 'USDA SR-28 #11135' },
    { nombre: 'Endibia', aliases: ["endibias", "endivia"], familia: 'verdura', rendimiento: 86, queSeQuita: 'hojas exteriores y base', fuente: 'USDA SR-28 #11213' },
    { nombre: 'Espinaca', aliases: ["espinacas"], familia: 'verdura', rendimiento: 72, queSeQuita: 'tallos gruesos y hojas dañadas', fuente: 'USDA SR-28 #11457' },
    { nombre: 'Espárrago verde', aliases: ["esparragos", "espárragos", "esparrago"], familia: 'verdura', rendimiento: 53, queSeQuita: 'parte leñosa del tallo', fuente: 'USDA SR-28 #11011' },
    { nombre: 'Guisante fresco', aliases: ["guisantes"], familia: 'verdura', rendimiento: 38, queSeQuita: 'vaina', fuente: 'USDA SR-28 #11304' },
    { nombre: 'Haba fresca', aliases: ["habas"], familia: 'verdura', rendimiento: 97, queSeQuita: 'vaina', fuente: 'USDA SR-28 #11088' },
    { nombre: 'Hinojo', aliases: ["hinojos", "bulbo de hinojo"], familia: 'verdura', rendimiento: 72, queSeQuita: 'tallos y capa exterior', fuente: 'USDA SR-28 #11957' },
    { nombre: 'Judía verde', aliases: ["judias verdes", "judía", "vainas"], familia: 'verdura', rendimiento: 88, queSeQuita: 'extremos e hilos', fuente: 'USDA SR-28 #11052' },
    { nombre: 'Kale', aliases: ["col rizada", "berza"], familia: 'verdura', rendimiento: 72, queSeQuita: 'tallos y nervios gruesos', fuente: 'USDA SR-28 #11233' },
    { nombre: 'Lechuga iceberg', aliases: ["lechuga"], familia: 'verdura', rendimiento: 95, queSeQuita: 'hojas exteriores y tronco', fuente: 'USDA SR-28 #11252' },
    { nombre: 'Maíz en mazorca', aliases: ["mazorca", "maiz", "maíz"], familia: 'verdura', rendimiento: 36, queSeQuita: 'farfolla, sedas y zuro', fuente: 'USDA SR-28 #11167' },
    { nombre: 'Nabo', aliases: ["nabos"], familia: 'verdura', rendimiento: 81, queSeQuita: 'piel y corona', fuente: 'USDA SR-28 #11564' },
    { nombre: 'Patata', aliases: ["patatas", "papa", "papas"], familia: 'verdura', rendimiento: 75, queSeQuita: 'piel', fuente: 'USDA SR-28 #11352' },
    { nombre: 'Pepino', aliases: ["pepinos"], familia: 'verdura', rendimiento: 97, queSeQuita: 'extremos (con piel)', fuente: 'USDA SR-28 #11205' },
    { nombre: 'Pimiento amarillo', aliases: [], familia: 'verdura', rendimiento: 82, queSeQuita: 'pedúnculo y semillas', fuente: 'USDA SR-28 #11951' },
    { nombre: 'Pimiento rojo', aliases: ["pimiento", "pimientos", "pimiento morrón"], familia: 'verdura', rendimiento: 82, queSeQuita: 'pedúnculo y semillas', fuente: 'USDA SR-28 #11821' },
    { nombre: 'Pimiento verde', aliases: ["pimiento italiano"], familia: 'verdura', rendimiento: 82, queSeQuita: 'pedúnculo y semillas', fuente: 'USDA SR-28 #11333' },
    { nombre: 'Puerro', aliases: ["puerros"], familia: 'verdura', rendimiento: 44, queSeQuita: 'raíces y parte verde dura', fuente: 'USDA SR-28 #11246' },
    { nombre: 'Remolacha', aliases: ["remolachas"], familia: 'verdura', rendimiento: 67, queSeQuita: 'piel, corona y raíz', fuente: 'USDA SR-28 #11080' },
    { nombre: 'Repollo', aliases: ["col", "col blanca", "repollos"], familia: 'verdura', rendimiento: 80, queSeQuita: 'hojas exteriores y tronco', fuente: 'USDA SR-28 #11109' },
    { nombre: 'Rábano', aliases: ["rabanos", "rábanos", "rabanitos"], familia: 'verdura', rendimiento: 90, queSeQuita: 'hojas y raíz', fuente: 'USDA SR-28 #11429' },
    { nombre: 'Tomate', aliases: ["tomates", "tomate pera", "tomate rama"], familia: 'verdura', rendimiento: 91, queSeQuita: 'pedúnculo', fuente: 'USDA SR-28 #11529' },
    { nombre: 'Zanahoria', aliases: ["zanahorias"], familia: 'verdura', rendimiento: 89, queSeQuita: 'corona, hojas y raspaduras', fuente: 'USDA SR-28 #11124' },
];